# paths to static input files
TCGA_cohorts: 'config/tcga_projects.txt'
signatures_file: 'config/gene_signatures.txt'

# params for survival_screening.smk
DPI: 400
THRESHOLD: 0.05
PERCENTILES:
  - 0.05
  - 0.10
  - 0.15
  - 0.20
  - 0.25
  - 0.33
  - 0.5

# define pathvars
pathvars:
  results: '/scratch/CBiB/soterino/smk_tcga_results'
  logs: '/scratch/CBiB/soterino/smk_logs'
